# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_address',
            old_name='name',
            new_name='consignee',
        ),
    ]
